# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 2  # Horizontal scaling with 2 replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: syedafraz/pythondeveloperproject:latest  # Replace with your Docker image
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/hierarchy_db"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"